-- Consulta sql dados ANAC:
Select
	EMPRESA_SIGLA,
	EMPRESA_NOME,
	ANO, MES,
	AEROPORTO_DE_ORIGEM_SIGLA,
	AEROPORTO_DE_ORIGEM_NOME,
	AEROPORTO_DE_DESTINO_SIGLA,
	AEROPORTO_DE_DESTINO_NOME,
	NATUREZA,
	GRUPO_DE_VOO,
	RPK
From anac_data
where EMPRESA_SIGLA like "GLO" 
      and NATUREZA like "DOMÉSTICA"
	  and GRUPO_DE_VOO like "REGULAR"


-- Tabela resultado consulta dados anac
create table anac_data 
	(EMPRESA_SIGLA VARCHAR(255), EMPRESA_NOME VARCHAR(255),
	ANO INT, MES INT,
	AEROPORTO_DE_ORIGEM_SIGLA VARCHAR(255), AEROPORTO_DE_ORIGEM_NOME VARCHAR(255),
	AEROPORTO_DE_DESTINO_SIGLA VARCHAR(255), AEROPORTO_DE_DESTINO_NOME VARCHAR(255),
	NATUREZA VARCHAR(255), GRUPO_DE_VOO VARCHAR(255), RPK INT);  

-- Carregando os dados do csv   		

LOAD DATA inFILE '/var/lib/mysql-files/dados.csv'
INTO TABLE anac_data
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS;

-- Dados analytic_data com dados tabela anac_data
SELECT 
	CONVERT (ANO, YEAR),
	CONVERT (MES, UNSIGNED), 
	CONCAT(LEAST(AEROPORTO_DE_ORIGEM_SIGLA, AEROPORTO_DE_DESTINO_SIGLA),
	GREATEST(AEROPORTO_DE_ORIGEM_SIGLA, AEROPORTO_DE_DESTINO_SIGLA)) market,
	RPK
FROM anac_data 